### ISSUE TITLE
Link specs to skills

### ISSUE THREAD

**Issue by RaphaelVSouza** [tiltowait/inconnu#8]
Hi, me and my friends loved your bot. I have a feature but don't know how to add, if you have time can you implement?

Connect the specs with the skills
Ex.: If I roll a Persuasion and I have a spec of seduction, I want the seduction to add points to my roll.

And if possible, separate specs and disciplines on character sheet

**Comment by tiltowait** [comment]
Hi, I'm glad you're enjoying it. Currently the way to do this is by adding a 1-dot trait using `/traits add`. You can also do this with `/specialties add` which is basically a shortcut to the former.

I've considered making "proper" specialties, but aside from organization on the sheet display, I'm not sure what it brings. It's a very complicated feature, both internally and from a UX standpoint. Since you can already do `/vr syntax:charisma + persuasion + seduction`, this is a low priority ...

*Unless* you can help me see a use case/benefit I haven't thought of?
